# Generated by Django 5.2.6 on 2025-12-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_question_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='theme',
            field=models.CharField(choices=[('professional', 'Professional (Blue)'), ('light', 'Light (Clean)'), ('dark', 'Dark (Night Mode)')], default='professional', max_length=20),
        ),
    ]
