# Generated by Django 5.2.6 on 2025-12-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_questionnaire_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
