# Generated by Django 5.2.6 on 2025-12-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_questionnaire_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('observer', 'Observer'), ('creator', 'Creator')], default='user', max_length=10),
        ),
    ]
