# Generated by Django 5.2.6 on 2025-12-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_invitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='created_by_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
